apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <CERTIFICATE_ARN>
  spec:
    selector:
      app: nodejs-app
    ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
    type: LoadBalancer
